document.addEventListener('alpine:init', () => {
    Alpine.data('excelEscapeComponent', () => ({
        active: false,
        level: 0,
        hp: 100, // Political Capital
        score: 0, // Efficiency Score
        logs: [],
        loading: false,
        
        // State Tracking
        playerName: '',
        playStyle: { manual: 0, legacy: 0, modern: 0 }, 
        gamePath: [], 
        outcome: null,
        leaderboard: [],
        isSubmitting: false,

        // THE LEVEL DATABASE
        allLevels: [
            {
                id: 1, name: "The Basement of Reconciliation", enemy: "The VLOOKUP Hydra",
                desc: "A 50MB spreadsheet crashes every time Finance opens it. The Regulator needs the report in 1 hour.",
                options: [
                    { label: "Split into 4 files", type: "manual", cost: 20, score: 10, risk: 0, msg: "Safe, but you burned out 2 analysts." },
                    { label: "Write VBA Macro", type: "legacy", cost: 10, score: 30, risk: 20, msg: "It works, but now you own legacy code." },
                    { label: "Python ETL Script", type: "modern", cost: 0, score: 100, risk: 40, msg: "High risk deploy... SUCCESS! Automated forever." }
                ]
            },
            {
                id: 2, name: "The Email Chain of Doom", enemy: "The Version Control Ghost",
                desc: "Three departments are emailing 'Final_v3_REAL.xlsx'. No one knows which file is the truth.",
                options: [
                    { label: "Call Emergency Meeting", type: "manual", cost: 15, score: 5, risk: 0, msg: "You wasted 2 hours, but found the file." },
                    { label: "Move to SharePoint", type: "legacy", cost: 5, score: 20, risk: 10, msg: "Better, but sync issues remain." },
                    { label: "Centralize in Data Mesh", type: "modern", cost: 0, score: 150, risk: 50, msg: "Single Source of Truth established." }
                ]
            },
            {
                id: 3, name: "The Boardroom Firewall", enemy: "The PDF Dragon",
                desc: "The CEO wants a live dashboard, but the data is trapped in static PDFs generated by a mainframe.",
                options: [
                    { label: "Hire interns to type it", type: "manual", cost: 30, score: 10, risk: 0, msg: "Costly and slow. CEO is unimpressed." },
                    { label: "Screen Scraper", type: "legacy", cost: 15, score: 40, risk: 30, msg: "Fragile. It breaks if the PDF layout changes." },
                    { label: "Build API Wrapper", type: "modern", cost: 0, score: 200, risk: 60, msg: "Real-time feed achieved. Executive delight." }
                ]
            },
            {
                id: 4, name: "The Deployment Weekend", enemy: "The Big Bang Release",
                desc: "It's Friday night. You have 3,000 lines of code to deploy. The manual test script takes 48 hours.",
                options: [
                    { label: "Order Pizza & Pray", type: "manual", cost: 40, score: 0, risk: 10, msg: "Team is exhausted. Errors likely." },
                    { label: "Delay Launch", type: "legacy", cost: 20, score: 10, risk: 0, msg: "Safe, but opportunity cost is high." },
                    { label: "CI/CD Pipeline", type: "modern", cost: 0, score: 150, risk: 40, msg: "Deploy in 10 minutes. The weekend is saved." }
                ]
            },
            {
                id: 5, name: "The Regulatory Audit", enemy: "The Paperwork Golem",
                desc: "Auditors want to see who approved every change in the last 6 months. Evidence is in emails.",
                options: [
                    { label: "Search Outlook manually", type: "manual", cost: 50, score: 5, risk: 0, msg: "Soul-crushing work. You missed a few." },
                    { label: "Export Jira Logs", type: "legacy", cost: 10, score: 50, risk: 20, msg: "Messy, but compliant." },
                    { label: "Automated Governance Chain", type: "modern", cost: 0, score: 200, risk: 30, msg: "Instant audit trail. Auditors are amazed." }
                ]
            }
        ],

        start() {
            Alpine.store('gamification').trackToolUse('escaperoom', 'sims');
            if (!this.playerName) this.playerName = "Agent " + Math.floor(Math.random()*1000);
            
            // 1. Reset Stats
            this.hp = 100;
            this.score = 0;
            this.playStyle = { manual: 0, legacy: 0, modern: 0 };
            this.outcome = null;
            this.logs = ["SYSTEM: Connected to Corporate Network...", "SYSTEM: Threat Scanning..."];
            
            // 2. Shuffle and pick 3 levels
            this.gamePath = [...this.allLevels].sort(() => 0.5 - Math.random()).slice(0, 3);
            
            this.active = true;
            this.level = 1;
        },

        makeMove(optionIndex) {
            this.loading = true;
            const currentLevel = this.gamePath[this.level - 1];
            const choice = currentLevel.options[optionIndex];

            // Simulate "Processing"
            setTimeout(() => {
                this.resolveMove(choice);
                this.loading = false;
            }, 800);
        },

        resolveMove(choice) {
            // 1. Apply Logic
            this.playStyle[choice.type]++;
            
            // Risk Calculation: Does the move fail?
            const roll = Math.random() * 100;
            let damage = choice.cost; 
            let points = choice.score;
            let logMsg = choice.msg;

            if (roll < choice.risk) {
                // Critical Failure
                damage += 30;
                points = 0;
                logMsg = `CRITICAL FAILURE! The ${choice.type} solution crashed. You took heavy political damage.`;
            }

            this.hp -= damage;
            this.score += points;
            this.logs.unshift(`L${this.level}: ${logMsg} (${points} PTS, -${damage} HP)`);

            // 2. Check Game Over
            if (this.hp <= 0) {
                this.endGame("FIRED", "You ran out of Political Capital.");
                return;
            }

            // 3. Advance or Win
            if (this.level < 3) {
                this.level++;
            } else {
                this.endGame("PROMOTED", "You escaped the factory.");
            }
        },

        endGame(status, msg) {
            Alpine.store('gamification').trackGameComplete(status === 'PROMOTED');
            if (this.score) Alpine.store('gamification').trackEscapeScore(this.score);
            // Determine Archetype
            let archetype = "The Pragmatist";
            if (this.playStyle.manual >= 2) archetype = "The Martyr (Manual Worker)";
            if (this.playStyle.modern >= 2) archetype = "The Futurist (Automation First)";
            
            this.outcome = {
                status: status,
                msg: msg,
                finalScore: this.score,
                archetype: archetype,
                hpRemaining: Math.max(0, this.hp)
            };

            // Trigger Leaderboard Save if Won
            if (status === "PROMOTED") {
                this.saveScore();
            }
        },

        // --- SUPABASE LEADERBOARD ---
        async saveScore() {
            if (this.isSubmitting) return;
            this.isSubmitting = true;
            
            const supabase = Alpine.store('app').supabase;
            if (!supabase && window.supabase) {
                 const supabaseUrl = 'https://qbgfduhsgrdfonxpqywu.supabase.co';
                 const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZ2ZkdWhzZ3JkZm9ueHBxeXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNjQ0MzcsImV4cCI6MjA4Mjk0MDQzN30.0FGzq_Vg2oYwl8JZXBrAqNmqTBWUnzJTEAdgPap7up4';
                 Alpine.store('app').supabase = window.supabase.createClient(supabaseUrl, supabaseKey);
            }

            const client = Alpine.store('app').supabase;
            if (client) {
                try {
                    await client.from('game_leaderboard').insert({
                        player_name: this.playerName,
                        score: this.score,
                        hp_remaining: this.hp
                    });
                    // Allow time for insert, then fetch
                    setTimeout(() => { this.fetchLeaderboard(); }, 500);
                } catch (e) { console.error("Leaderboard Error", e); }
            }
            this.isSubmitting = false;
        },

        async fetchLeaderboard() {
            const supabase = Alpine.store('app').supabase;
            if (!supabase && window.supabase) {
                 const supabaseUrl = 'https://qbgfduhsgrdfonxpqywu.supabase.co';
                 const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZ2ZkdWhzZ3JkZm9ueHBxeXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNjQ0MzcsImV4cCI6MjA4Mjk0MDQzN30.0FGzq_Vg2oYwl8JZXBrAqNmqTBWUnzJTEAdgPap7up4';
                 Alpine.store('app').supabase = window.supabase.createClient(supabaseUrl, supabaseKey);
            }

            const client = Alpine.store('app').supabase;
            if (client) {
                const { data, error } = await client
                    .from('game_leaderboard')
                    .select('*')
                    .order('score', { ascending: false })
                    .limit(5);

                if (data) this.leaderboard = data;
            }
        },

        // --- PROMPT GENERATOR ---
        generatePerformancePrompt() {
            if (!this.outcome) return "Finish game first.";
            const o = this.outcome;
            const p = this.playStyle;

            return `ACT AS: A Chief Technology Officer (CTO) conducting a performance review.

## THE GAMIFIED ASSESSMENT
The candidate played the "Excel Escape Room" simulation.
- **Outcome:** ${o.status}
- **Leadership Archetype:** "${o.archetype}"
- **Final Score:** ${o.finalScore} (Efficiency)
- **Political Capital Remaining:** ${o.hpRemaining}/100

## DECISION STYLE
- **Manual Work (Grind):** Chosen ${p.manual} times.
- **Legacy Patches (Band-aids):** Chosen ${p.legacy} times.
- **Modern Automation (Risk/Reward):** Chosen ${p.modern} times.

## YOUR MISSION
Write a **Performance Feedback Email** to this employee.
1. **The Profiling:** Analyze what their playstyle says about their real-world management style (e.g., "You rely too much on heroism" vs "You take smart technical risks").
2. **The Career Path:** Based on this, should they be promoted to Architecture (Strategic) or Operations (Tactical)?
3. **The Book Recommendation:** Recommend 1 real book (e.g. Phoenix Project) based on their specific failure/success pattern.

TONE: Mentorship, tough love, growth-oriented.`;
        },

        reset() {
            this.active = false;
            this.level = 0;
            this.outcome = null;
        }
    }));
});
